from datetime import datetime
import argparse
import subprocess
import math

CODON_USAGE = {'*': [('UAA', 0.28), ('UAG', 0.2), ('UGA', 0.52)], 'A': [('GCU', 0.26), ('GCC', 0.4), ('GCA', 0.23), ('GCG', 0.11)], 'C': [('UGU', 0.45), ('UGC', 0.55)], 'D': [('GAU', 0.46), ('GAC', 0.54)], 'E': [('GAA', 0.42), ('GAG', 0.58)], 'F': [('UUU', 0.45), ('UUC', 0.55)], 'G': [('GGU', 0.16), ('GGC', 0.34), ('GGA', 0.25), ('GGG', 0.25)], 'H': [('CAU', 0.41), ('CAC', 0.59)], 'I': [('AUU', 0.36), ('AUC', 0.48), ('AUA', 0.16)], 'K': [('AAA', 0.42), ('AAG', 0.58)], 'L': [('UUA', 0.07), ('UUG', 0.13), ('CUU', 0.13), ('CUC', 0.2), ('CUA', 0.07), ('CUG', 0.41)],
               'M': [('AUG', 1.0)], 'N': [('AAU', 0.46), ('AAC', 0.54)], 'P': [('CCU', 0.28), ('CCC', 0.33), ('CCA', 0.27), ('CCG', 0.11)], 'Q': [('CAA', 0.25), ('CAG', 0.75)], 'R': [('CGU', 0.08), ('CGC', 0.19), ('CGA', 0.11), ('CGG', 0.21), ('AGA', 0.2), ('AGG', 0.2)], 'S': [('UCU', 0.18), ('UCC', 0.22), ('UCA', 0.15), ('UCG', 0.06), ('AGU', 0.15), ('AGC', 0.24)], 'T': [('ACU', 0.24), ('ACC', 0.36), ('ACA', 0.28), ('ACG', 0.12)], 'V': [('GUU', 0.18), ('GUC', 0.24), ('GUA', 0.11), ('GUG', 0.47)], 'W': [('UGG', 1.0)], 'Y': [('UAU', 0.43), ('UAC', 0.57)]}


def build_cai_weights(codon_usage):
    w = {}
    for aa, lst in codon_usage.items():
        if not lst:
            continue
        max_f = max(freq for codon, freq in lst)
        if max_f <= 0:
            continue
        for codon, freq in lst:
            w[codon] = (freq / max_f) if freq > 0 else 0.0
    return w


def cai(seq, include_stop=False, on_unknown="raise"):
    if not isinstance(seq, str):
        raise TypeError("seq must be a string")

    s = seq.strip().upper().replace(" ", "").replace("\n", "")
    if not s:
        return 0.0

    s = s.replace("T", "U")
    weights = build_cai_weights(CODON_USAGE)

    logs = []
    L = 0

    n = len(s) - (len(s) % 3)
    for i in range(0, n, 3):
        codon = s[i:i+3]
        if not include_stop and codon in ("UAA", "UAG", "UGA"):
            continue

        w = weights.get(codon)
        if w is None:
            if on_unknown == "raise":
                raise ValueError(f"Unknown codon '{codon}' at position {i//3 + 1}")
            if on_unknown == "skip":
                continue
            if on_unknown == "zero":
                return 0.0

        if w <= 0:
            return 0.0

        logs.append(math.log(w))
        L += 1

    if L == 0:
        return 0.0

    return math.exp(sum(logs) / L)


data = {'peptides_30': ['EAKIIFEVDWQCADHITYAVHVQIRWKAGQ', 'MKFHMEDPENNYKCRVEPDVLYNWHDCILD', 'IEPKRNGNNHKDYGVIGRPKVIMCICMPKD', 'HWMHSPRFKFIVVKWQWPNIFTSDCEFGQY', 'DPPYRTKVAEVKMELQGRAKTGTELTYHFN', 'GVTAYMSAENLICIWDDSDVFFSVGKTYQH', 'VHLPNRTREIIDMAWVIWIADCIDCMDTIK', 'SHVFWWSISQHEEQNQQRCECPMEIHHVRF', 'QGKRIDRVECVADIGQSSHPCGPAPKRLQV', 'SFHLHCWVCMCCWSTTGCTDGDYDIPEWIW', 'YCYDQWWTMKHMIKPFLRMDARYWEDVHTK', 'FNDINLGRVLYTAVLEFKEEVFKLYHMHKT', 'SKCDQKCAMFKGRVQVAEDFVCNWVFQFCL', 'NCNHIENVQYFIGGQAGMQIKGEPCSIHRN', 'LIIAHPMKDKNTPVMAEKGWKCEYQNMQYT', 'EPWHKCQATVHNQDMYMELTLQMPLVFHQP', 'GYWLPVALLHQWYMRRRHTSGDLTYMDILI', 'HFACISYDRQWHPSPIFAEQIGTRCVIERF', 'RTVYMRYTQVRGSRKIKTSIKRDLIKMMVD', 'FFIPFHDQQMVRQCHQPWAWPSANLPQVVY', 'ISIKQSAPMPGRFYVAPWWADQFRGCKPMH', 'RMMPKQKDSAVCNIDCAIHAYFIFSEWHRK', 'NGYYEGLEWALWPPHDWIELYEWCNVQNDT', 'MAQSEQNRFQGTKYVSRQWKMIDKRIRWYP', 'MASMGSHNKMKYKVATHDIQSVISSRADLI', 'PILWNSVTNQVMNRKLKIEHMEVGHHSKWT', 'YLEHLINGLAVFKCCVLFSEAWLSSRMGCK', 'SEDPSDWCFFWLDIEVQYYYITPRRLWQLW', 'YCYEHHKDGIGVDGAQRYSLCILLRDIKWH', 'QEVIFKFDCGLYWLRERLPKTVSRDYCQMY'], 'peptides_60': ['KADIWWAKWCGSTRKGWQSDSNQMMEGMQSLPVCRDMKMEPTAVRQCHTNYSRCHKVFLR', 'SEAYIGLVAVQDIEREFSLTKQSSIRVFPHYTFDKQMTKALLWWSFRVSNMVVPRMHIWP', 'IQCMSPPFSCFTWMERETRAFQFDSKMYPDMVPMSVCYDILIDQEERGLACMCLNNQFIT', 'QWGGGDYPYISWFIRKRKARLVGDRNWLQKRLHPSEIPWNWLLAPKAWCYSLIYNIHYKF', 'ECLRCWNFDLMQGHFVNTTKGKSLMERDFIPVNDPAKVERNKWPNEISAYVMYIDRLQEF', 'CCLSEEIVFPRNVQWFQESYQKCNHRRINENVNCPKHERDHYACMIFWHDVHWHIMFYAK', 'FFVKGEAFANIWMAGKCFQTEDSRNTWERTIYCTLRACSPQESRDDMYFDFKYWVMPYTL', 'RTYQEEVHQRIQMRPQEMQMKNFSDDDDQENFVCWVVMEQNQCLYLNEWTHFSIENVNEK', 'WIQVYYVAYKAGKLMNAGFWPDFADTHPQRMGNLMWYDCFGYCDKRQSYRQKHTENQELW', 'STLCIPYCAHLHFKLMEASQGFPVITVNDPCQARDMWQWPQLEPAMGYRNDQEIQWPTDP', 'LMIMGDTETTHNNFIEFKHGYFDGSRWWRWYMMFRDSRLKWCNTDLRRCCNLDDYYTPRW', 'VCRWHMYSTFCREMDTGCIRRTTYGNNLPQMYCMDMEVPLKYFMDWFNLPFYDLVPMFTD', 'QTNANLGHMSHIFFDLETVTCMYFYPFGGYGRCQNIRYLRIVILSHNWRRLPTTQGHYFK', 'CSNVETELDGKRTFQDIRNAQCPTNIPDNIAMEMFFCLSFSRYADAKHFVYTQELILECI', 'QYRDESYVATWIFLQAYNIWQGDTNDTVTTVAPSCPNKANDNIEWMFCNVMGRSGFDRCL', 'HCHCMLTPVSKCHLNCMKENQPRPMGSSNTKDQDQYGVLMEDMLLRYQGRNRCNYQKCDP', 'NTGAFYRCFDINNPWCYFRNNRDWFTNPMKIEAGSTPVEKKRHYLSHEFDRGRDMNDVVL', 'LGGNTIEHFISANVWNRVFYDDLPSTQQWDFMDRRTNFVWGFQTCETFLGGMINTLDKHV', 'KFLYVDTGWWFGYYMWCADCWKHWQYASVLLSIPLRDCGRQSRHMYFMMNPFNTVEMIRE', 'KRIFECLPYQIGMWMHGSTRSLSADPTRIHWNCCLSYSLVAEQFKNPNCPCWVHNVLDPT', 'RVKYYEFEPNMVNFHYTPTCCCFMSTRFYTFMYMGPYLWMTTVSWLSANMEQWLAYSKWW', 'ICWSGTYPFICWEHARMQFQHQTYSCFTHVMSTPMGRVMVNKYSHIKVLILLHSMSNVKL', 'EWVPPNFLCLDNRKSHHVKVKFEYWIICTIICEQMSEFAVGQSSHLMLCDWIVCGQGCPS', 'GLCALWYEMLRVTSFTRKHEMGRKGAMLWHGYPQTMDPEGFSMIAKPIRKMLWWAKNICE', 'RLGPTLELNYIIFSFRYNQVSVHIYDTRTNDWECVTHWVFGMTREHWSDTRCRFTQRWCV', 'RLAPKAHWDCQNDVCDSCLQGFQNPRPPDVFNEGVPTFIAALRVQVPIIRNFKHECQYAI', 'HDEYCRYCICPRIVHCFTLIWMWYMILFTIQLKCVWGQVSCNPTMQQFLPGVSIILFRCV', 'QQVTFPIKHMDRNDVHCKPYYCDHWVHSHMLAHHESIYHPIVMLPRVNLKNTSRESMHNM', 'QCWIFAKVWWQLFHMIPWISVMKSSRGNGFVSGVCTCDCAQFIDFAHTRNCYYSSAAVVQ', 'AATKVLATQGEETFIHYTKNKPDNPRWIILDCDPPPVSCAGDSQMWETCIHWSKCDKVWC'], 'peptides_200': ['GMAHWFPDLGWIWPVMPFDTNCEQIDMYYYPMAKRSINVPQGWPDYLIDDKFPFPMNEDALRNKEFDGQRVVTQEADNVDYYMPALQPDVIWTGPGFKLKSFDGQKQLSDNKISYYHREFLAPMYPMRMQYFLMYHSMGPMLSWIMPKPNEWHWVGVARHRLDQSFLIKFQPDRYSWPVTQVCNVYDEINGYCWPMQEAE', 'KITTVWWIRNPRWTFNASELQDEFNLMRHTSNSERRMDLCEAMEGITGVGMVQRIPGGQPAYHRWQPAHHKDWEVGNMHREKSTMYPYPWENNRYGLYWDFMEILEGNFTPQYFWPQGSVGVGSLFGMRYCNASFHPVTSQSQRSGDWAILCKIVLGRWSVTEWEKVNVCRVHQEILCRKNDREIHWNYQGYFHHCWNVK', 'YVGMLLWKTEFQCKFFIFMIPSFWKQPRDDPTKNRSMWADRNDVPHQHSKMLMVWFWSMCCERAEGRRAQHFLGKDNKDNGCPLIQDEAHSDFWITRAAMEQFSDIPDEEMNLFPFFDTWAYGRNHFQYRHDEFEWPNQMFIKDIVYYYLALHTYTHPLCISPEISYDTANMFPWQNVGSDAWDAKHCCPTLTQQPDVVY', 'FKDLDTHFVMPWDLQICIDQERYYCLGEAFAGSNTTKGNFKEAMQKTDKWDSRTNCSWGNGKEWEITACAICSNPFGCVQIMIQMKDWNETCGITCPDRLLMDVRANHLWLYIRNWSHVIFAQAIVNAMAPLEHTIQSCFKDCITQNRDWETFPDWWCQFILKMPMMRKIDHFWEFEGRRMQEVNHRLRKEDGLYCHMFD', 'INPTCLKGAPRVVIEREFEACIFHPNDWWKDADHRFDMECRCGWQPSAPQGNHGKKRFCYYYILSQVSCDKPFQHTIVAPNSVSNWTMPKGAMYIAKCSTNWIGEIIKVCIWPNGGIWMNWANWWFWHSVLGSCDCIYIATSAMYHFMGMCAFWFETNDNPWEMLMFGQSMGVYNIWGPLLFGAWPWCGYMYIWESFMDI', 'NMGDMRAKHIDNKEACPRQGQSPNVPESWIGRDCLAMKEDMGPGDVDMYYSAQGYQGCEMHHQVVKLLIECPWVSFCNAQDLYSHEAHGLDSELPSSKDVPGNPNGRCKRRKIKWCFEDNVQWIVCPTQVSWISLDPCTWTWYFERGGHHFCQDQHFYKMDDPVPVMKTRAYWTQEQFFWWWEEWELVNQKPSWYSCGKP', 'FYYPCPMICSKNAMLLKSEIFLRMKQYDHRHQSTNCTGDLTPFTWAGHHCICRCNHKNRTPEAINSYRGSWVNNGKDLAPCGWHIIHKQTAASFGYAIKYLKQPNRKHRLTYPWEATNVYYLLESDMKMKKLHFTICYPMFASLKQPPCWWHMIVSNTLGVGLESFKVGMDINILQMNKWLRESCWWYDSHTEPTLQCFF', 'HMQWRFMGDSMGMCARKHGWGSDFYQQPQSPACVHNAMTHAAIINLFEPTWLGDCLLRTYTMQFMSNHGPAIIFHAWTGENCPKVYCYCEACEQRPEVKSFHALQETKYYFQETYELEESHYHKTHNQLGCVSHSMIAADEWSFDTDEKIRLKRCEGCLNMQEECAFGMNRYKDNMGEPPRKPSQGEFCGEQWSWRGYPN', 'YAFSSEQRCDKMATWWIMTTYEQISNPFVYCAGTSSGDSMIMKCTIVPPIDRRWRDSRMESAEPQCVVADYYLTVHRMNCIRMVYYSNREEIAMNLVTNECGSFQEKYHHEPHRHMEQCWERRWTFSATCVQWSTGWGFEPYYMTPQYIKPMLRFFQYTLVMVHHHYLNFGTVMENVSWWQVLQATEAPFCCHKGLKFCL', 'HVCNREYVIVPITLCPPQMVCAKHYRINWVYHHLRGDGGTEPCQKVKFGWKAMRFCFMYCYLSWVNDMTIGTDTGQVVPDNIHMMNLHYTSVAENRIYYICMPEPKVLATNTTRSCLHMTDEGVVADHHQEHVQDFARMCDDCGKVDWIKQPRPQMAPEVAYDWCDNTELLYDLRPPASGVIFPVLFLNAVVFECAWYPV', 'VDLHNHQTFGGIYKHEGWCVRVDLDKEHWSMNFIELYDHMSRMYLWFWWNMQGAMIIQKNFMSRRNLSVEGYDKFVHKDDATAWWPWHCVKVVSFNPIWLFRTTDPNTAIYGTFRGGWWFSNCISIDKNICHTNPSRCCMETKKWVWGPPNWDTKPITPNNSSYATFRGIDTKHFGGNYEIQMESSSHWGQAICFWWGFT', 'CWFCGKGTPYWALDHRYSSGIQYFWGYTKGMRYWDIPPFEAHTTQFYEGSYYCVTEDSFYVAQTQNCTQISPNWWEQFKSIDLYVQKHAAWTETAPHMQNEFQWKKVQWNYKPHQVVSGNVVSKLWNPFEIRGEHTPMVYCGPADFSYQDDKINDYCPPYTLYCGSRAHTLHCYTTIYGCNIAGDKPNPPWHTADDVLVW', 'NNKIYHRPWAKGQTEVDTLMETKVWKRPWSIMRRWASEKDPIIMQNTVAKILDPMDVGSMNHWKGHSHIIKHIHIYNFEEDSYAVCSNYMSWKSGTKPIWFCTQSVCTNPGRETRMAAHPWEMNYKGVKIKSYMNGSQHQNNPKRGWFWIEKIVQPHFFSAGQSFTVMSLKVWCPEGCHKSERMKNNVVKNAQENYHWWV', 'GLNMTSRDPYLRFGMQYWPDDGMIMMLKYPKRNWTRQGGAFIKDHGPEEDSVCAPTDEKYFDPLIILRFFTGACNMSRVKVRFVGWYRWQTVLNSVIDRLNQKFLAATFNLSVASSLAQLYIAVNHQVQPIGPPIKDQITYKLVKQHDGFLERYRKYSHMAFCVAGELKFRAIDFASHMQLSNRCMDFCKPDVSGHKPAE', 'IPRICHRETHSPLMGCVTEKSLHNCHEIQMAGKWEPIACWSYFNDIGSDYMCCNFVEFSIMVNRHAPNFKCSRVLVSHWGVNMRKYVGDTFRLKVNRATPGAYNYIMDVPHTSVFYLMQMEETDCFGCHESHECWPSTYWKCNIYDAHSDRCNVQNCYKTCDLDHTEEIVPHHTIWGVVQEWNRQEGGVPTMGVYRNMVM', 'NQQMYIWVHPVKNRRPACLYATFLALIHMAKVTVWWFECRNFFKNWIIKLDWPWHDMSGSWEYLCWPDCMNQQEIYAPCLTCMVWFMTIFCPRYWTDIQLPFFMDSWCVPKDPTQFFSVHSPWHVYTIIDKQMWDEQQNNHMNYALGNYRYFRCIHNFDECIYFLAMELRSAMHVHHVTKVSYFAPWTCKGCLHYKCRAD', 'PKNEALPIPTEMSYVDGHTRVACITLMSPGANNNLITKCKPAVKIFMPFDPTYIQIWFQLYMRVFHFWVHFLTFQFWGMDVVEGMFAMQQLRKFHEFGAYYKYWYIYIIANDSFTYSNGPSSFGHICQAKQIHHDGRYSMRIQPCYPMPYWYVTCTERRCITVPCVPTCHLRPLLRGQLYCTFRRDTEGWVFPQMRAGRW', 'HRDKMGEDERNDTPTYGPVPCGMWFGFGCQLLRLGEFHAYKARSSVAYSIHWSRQRDYYAIVKYVHCGFCNCFCWYLMDCEQGGLYYWVGRWNCDLMNPDQVDLSFEKMTQTHHYCEWTDSYLQYMKTWYNFYWSTSSGYILHAEAREHYQQCMNVHAHLKDLLTVMAEMMPWYAGHMMSSCFSFRVMRQCTLWMVVAHW', 'MNDFKAMPVGWYPGYELMCKQDSINRLHTLGENCHDRTASTFHMSTLMFETFHCRPTEALCYDMRCETLAWLHMHHLKVMREKFGKEAYVTEHVNVMKFLWIGDLYMVRCFASCEPCDQPGYWRYNLMHVDRWFDRERLRSIIFYKNPGMMRSADSENSRGLNYWFTEPEMVDLVRPWQIYIVGSPDMHWQQWMVIGDWS', 'EWYRMVERGLPDYEYPMSCDHFWAFFRVLPYWRHHMLWLQNDWAYTPFLCNVCAVNELAIQWPMPPPQVHGSFHVPNQFLFFADAFSQFDFQRYQYGRTQVRPNIGQYAWSITKQVWNCCWSNEWSDFTKRTDTYDISDVWLYCMVASRTSWMQNLLGCYLWKCSWGWCLYALSDFTDKKFYKKKAEYGWFRNGKISGTC', 'MDFYFSQPIRGHWNCKECGRPSLSVIPPSKFTQALRPMTCEVNQYKMKKEKWPRIWHTMGMVAADAQETERNILKHCAYDCYHYEEDYFPWGEGKLRDRKQMKGDKCPPMCKKGRDSHYPGSEFVQHYERKECDDWKRASFACPKFMPWATSSQPDVIAPSEWVNMLPCDNVMDRLHGVCPHLPENSDRHFCHAWISPDV', 'LSVRACMCMCPEHTRVFWIDCFSASYCIFAGCLERYGWDEESYYIDHQMPMEWVFMHCWGMDEKFQGNVGRIWCFEYPGASDAAGDWLQSFHFKTRQIGYCYGSYDLNQAVIHETEYNVTIRHKCHEFSSGGCCNLHQKMYRCECVGGASTEDIRWWMQHMIEMIEIQHPIDSWSCQFHYRGPNFRHNKHMFCWCKFERR', 'QGMILYGYGWVIDQTSHWSRKAQIIMQWIWFWAQCCSTCQTPSERSIDVAQHFNLIDASLGRWWARRFPGNRADPMTCLQKYVWHDYMCTNCEPNRYCNNGVDVHFMIVESWHIMNKTQKCDNNRSTTESVVLRYNDHRDDPGLDEGKEFSFHTALQVFSNQRALHDAITMQWMMSWTVRRLWFLGKISNLCFNLRGYGV', 'LGGFGIECMWFRKNGHVCMNFNRVGVLEAPSFRMFAVTMLSLWFWRMESCFVELAPYIRNDMCYHWTIKHADVRDTPHSMYYTCNPFQNPNALNNLRVDHRQRLGQQFWYDFHLSTMDWPDAQKQGVRWFHGPLVSCLWLSVRIAAFKLSELQGSIAEKSDYNWSWQKSENTWAKGWCFMRFNGCKNQNCLLTDTHGEYG', 'VMMLKNEVWNFAFTLNSQMGEHFTIHVYTVVEQRDEFASNLNFRYTMGLAEIFFILFHFDQEDASQCHECTWCSEKCDLAEEYHWHGNADFKWNNGTYITWDEWATHHLGVAEHTSNWGREGNPQHTIQEMERETFSNLVCDMSEPLRYLRIVQLHDSNGASEPRTDEFPPWEGDNHMHYPEIQSKWWKPNSYPSTKFR', 'EEKSSIFAECDSAGPYMFLYYEDTSRHLSSTKVMVVACQEPRMPRRCCGVLGSQFLPSEWSVVWSSVGTCPKSWPYNLMCAWCFNNWAMPEQNNQNCIIILWDDLEMGAVMCRQWTQKASWAMPWPMWESEHMSTMGYLNQHSDVHLKCLWPIYDWEWMKDWTSQHNDLTLQVMHQPKYTRVGATGWSHRKVYQWCTHNR', 'FIFLQQMDHQKLGKYIPIEFHAILRSVQQCHGKFAKKVGCSACDMYLDQNDPFIEWTETWTKSDIYEMMWPIQHFEGHKRQKWCSVNEMVQSIKFNSNLAYCCIKVPLNEVIRPAPKLDILHGRMQCKDSSQMQEGKTDNQYVMRACGRFAPHLMWDEGITFYQMRSFKGWMLHDQNGPPWIAAVYIDRHKGCPYQYKFD', 'NGWEATQRSEIHHKLSPFQHYHLHQGQFALKIYRINWRDASFMPHPQYKDEVCCMISNYYCAKTYPLPNFVCWGKGTSMRFDMTQFKEMCFSKNQLKYKTMQGMSFVRCHFCIGCSKGRQESCRNVSRSEFENDHLGGTKWWHWATWGQDISEMALEPNWEMFADRSRKYAMCYRMWFHCLMCDVYPDPKGIPDAHGPPL', 'FELSQLYFNENTHSRPSKWYQDQNYGQQDCTMRIFSTTDLRQDSLFFLITQLWCVDCTETQQERWKNKWDTAERGGPCDQLMWRRYKMGHGDYKEQVAAPEAGSRPYSLYYNPLDFFAHEAHAHSFIQVHDLRFSQAEGFRSSARWIHLWPCMAEQQSWYVLCSPSTWYSICTAQWMVDKQSESYNRQAGLHSNRITIWM', 'YRFLPQNSGYHLDSFGHGYSEQSLIHVCANKNGGTCDMQEYIEVISKMNCVKFTYECRREEYYEVCTEGEHNGLRTSEFNMFEHRQAISMLTGDKNQNIFTQIFQQQRTNARFATDDMMPGQCPCFWCTLQPVLMNAKTYFPRHVYYRNPHLDCVMPFTVLHDTVLTMGAAVWKILQTECNKTNECERLWARMIWWVYIN']}

prefix = "TTTATAATTTCTTCTTCCAGAA"  # IRES=22
suffix = "UUAAGCUA"

beam = 500
iters = 10
lr = 0.03
L = 2.5


def exec_cmd(props, input_text, cwd="./"):
    proc = subprocess.run(
        props, input=input_text + "\n", cwd=cwd,
        capture_output=True, text=True, check=True)
    out_lines = proc.stdout.splitlines()
    err_lines = proc.stderr.splitlines()
    return "\n".join(out_lines + err_lines).split("\n")


def find(lines, q):
    for l in lines:
        if q in l:
            return l.split(":")[1].strip()
    return None


def colored_ires(seq, start, color=31):
    return f"\033[1;{color}m{seq[0:start]}\033[m{seq[start+1:]}"


def count_cross_pairs(s: str, k: int):
    stack = []
    cross = 0
    for i, c in enumerate(s):
        if c == '(':
            stack.append(i)
        elif c == ')':
            j = stack.pop()
            cross += (j <= k) != (i <= k)
    return cross


def EFE(seq):
    res = exec_cmd([
        "./tools/LinearPartition/linearpartition", "-V", "-d0", "-b0"
    ], seq, "./")
    val = find(res, "Free Energy")
    return float(val.split(' ')[0])


def EnsembleWrapper(seq, init, eps, ires_end=0, lam=0.1):
    params = ["./bin/EnsembleDesign"]
    params += list(map(str, [beam, iters, lr, eps, 1, init]))
    params += ["--prefix", prefix, "--suffix",
               suffix, "--iresEND", str(ires_end),
               "--lambda", str(lam)]
    res = exec_cmd(params, seq, "./")
    mrna = find(res, "Final mRNA")
    print(" ".join(params))

    res = exec_cmd(["RNAfold", "--noPS"], mrna, "./")
    struct = res[1].split(" ")[0]

    crp = count_cross_pairs(struct, 22)

    print(f" - mRNA:  {colored_ires(mrna, 22)}")
    print(f"          {colored_ires(res[1], 22)}")
    print(f"   CROSS: {crp}  [for {ires_end}]")

    return crp, mrna, struct


def frange(start, stop, step):
    x = start
    while x <= stop + 1e-12:
        yield x
        x += step


def main():
    parser = argparse.ArgumentParser(
        description="Faster subset of test-random.py with the same output format.")
    parser.add_argument("--per_set", type=int, default=10,
                        help="How many proteins to take from each set (default: 10).")
    parser.add_argument("--eps_step", type=float, default=0.2,
                        help="Epsilon step for frange(0.0, 1.0, step) (default: 0.2).")
    parser.add_argument("--lambda_value", type=float, default=0.1,
                        help="Lambda passed to EnsembleDesign (default: 0.1).")
    parser.add_argument("--output", type=str, default="",
                        help="Optional output file path; default: test_lite_<timestamp>.txt")
    args = parser.parse_args()

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = args.output if args.output else f"test_lite_{ts}.txt"
    res = open(out_path, 'w')
    res.write("sid\tires\tEps\tLength\tCrosspairs\tCAI\tEFE\tmRNA\tStruct\n")

    sid = 1
    for eps in frange(0.0, 1.0, args.eps_step):
        for set_name in data:
            subset = data[set_name][:args.per_set]
            for seq in subset:
                tmp = exec_cmd([
                    "./bin/LinearDesign_2D", f"{L:.2f}", "0", "codon_usage_freq_table_human.csv"
                ], seq, "./tools/LinearDesign/")
                init = find(tmp, "mRNA sequence")
                for ires_end in [0, 22]:
                    crp, mrna, struct = EnsembleWrapper(seq, init, eps, ires_end, args.lambda_value)
                    cai_val = cai(mrna)
                    efe = EFE(mrna)
                    result_line = (
                        f"{sid}\t{ires_end}\t{eps:.1f}\t{len(seq)}\t{crp}\t"
                        f"{cai_val:.3f}\t{efe:.3f}\t{mrna}\t{struct}"
                    )
                    print(result_line)
                    res.write(result_line + "\n")
                sid += 1

    res.close()
    print(f"Saved results to: {out_path}")


if __name__ == "__main__":
    main()
