from datetime import datetime
import subprocess
import math

CODON_USAGE = {'*': [('UAA', 0.28), ('UAG', 0.2), ('UGA', 0.52)], 'A': [('GCU', 0.26), ('GCC', 0.4), ('GCA', 0.23), ('GCG', 0.11)], 'C': [('UGU', 0.45), ('UGC', 0.55)], 'D': [('GAU', 0.46), ('GAC', 0.54)], 'E': [('GAA', 0.42), ('GAG', 0.58)], 'F': [('UUU', 0.45), ('UUC', 0.55)], 'G': [('GGU', 0.16), ('GGC', 0.34), ('GGA', 0.25), ('GGG', 0.25)], 'H': [('CAU', 0.41), ('CAC', 0.59)], 'I': [('AUU', 0.36), ('AUC', 0.48), ('AUA', 0.16)], 'K': [('AAA', 0.42), ('AAG', 0.58)], 'L': [('UUA', 0.07), ('UUG', 0.13), ('CUU', 0.13), ('CUC', 0.2), ('CUA', 0.07), ('CUG', 0.41)],
               'M': [('AUG', 1.0)], 'N': [('AAU', 0.46), ('AAC', 0.54)], 'P': [('CCU', 0.28), ('CCC', 0.33), ('CCA', 0.27), ('CCG', 0.11)], 'Q': [('CAA', 0.25), ('CAG', 0.75)], 'R': [('CGU', 0.08), ('CGC', 0.19), ('CGA', 0.11), ('CGG', 0.21), ('AGA', 0.2), ('AGG', 0.2)], 'S': [('UCU', 0.18), ('UCC', 0.22), ('UCA', 0.15), ('UCG', 0.06), ('AGU', 0.15), ('AGC', 0.24)], 'T': [('ACU', 0.24), ('ACC', 0.36), ('ACA', 0.28), ('ACG', 0.12)], 'V': [('GUU', 0.18), ('GUC', 0.24), ('GUA', 0.11), ('GUG', 0.47)], 'W': [('UGG', 1.0)], 'Y': [('UAU', 0.43), ('UAC', 0.57)]}


def build_cai_weights(codon_usage):
    """
    codon_usage: dict {AA: [(codon, freq), ...]}
    return: dict {CODON: w}, where w = freq / max_freq_for_that_AA
    """
    w = {}
    for aa, lst in codon_usage.items():
        if not lst:
            continue
        max_f = max(freq for codon, freq in lst)
        if max_f <= 0:
            continue
        for codon, freq in lst:
            # w in (0,1], but guard zero
            w[codon] = (freq / max_f) if freq > 0 else 0.0
    return w


def cai(seq, include_stop=False, on_unknown="raise"):
    """
    Compute CAI (Codon Adaptation Index) for a coding sequence.
    seq: RNA or DNA string. (RNA: A,C,G,U) (DNA: A,C,G,T)
         Must be in-frame (len % 3 == 0) unless you allow trailing remainder.
    codon_usage: dict like your CODON_USAGE {AA: [(codon, freq), ...]}
    include_stop: if True, include stop codon weights too (обычно False)
    on_unknown: 'raise' | 'skip' | 'zero'
        - raise: ValueError if a codon not found in weights
        - skip: ignore unknown codons (reduces effective length)
        - zero: treat as w=0 -> CAI becomes 0
    """
    if not isinstance(seq, str):
        raise TypeError("seq must be a string")

    s = seq.strip().upper().replace(" ", "").replace("\n", "")
    if not s:
        return 0.0

    # normalize DNA->RNA (T->U) so it matches CODON_USAGE (which is RNA)
    s = s.replace("T", "U")

    weights = build_cai_weights(CODON_USAGE)

    logs = []
    L = 0

    # process codons in-frame
    n = len(s) - (len(s) % 3)
    for i in range(0, n, 3):
        codon = s[i:i+3]
        if not include_stop and codon in ("UAA", "UAG", "UGA"):
            # обычно стоп не учитывают
            continue

        w = weights.get(codon)
        if w is None:
            if on_unknown == "raise":
                raise ValueError(
                    f"Unknown codon '{codon}' at position {i//3 + 1}")
            if on_unknown == "skip":
                continue
            if on_unknown == "zero":
                return 0.0

        if w <= 0:
            # нулевая частота => CAI=0 (геометрическое среднее)
            return 0.0

        logs.append(math.log(w))
        L += 1

    if L == 0:
        return 0.0

    return math.exp(sum(logs) / L)


data = {'peptides_30': ['EAKIIFEVDWQCADHITYAVHVQIRWKAGQ', 'MKFHMEDPENNYKCRVEPDVLYNWHDCILD', 'IEPKRNGNNHKDYGVIGRPKVIMCICMPKD', 'HWMHSPRFKFIVVKWQWPNIFTSDCEFGQY', 'DPPYRTKVAEVKMELQGRAKTGTELTYHFN', 'GVTAYMSAENLICIWDDSDVFFSVGKTYQH', 'VHLPNRTREIIDMAWVIWIADCIDCMDTIK', 'SHVFWWSISQHEEQNQQRCECPMEIHHVRF', 'QGKRIDRVECVADIGQSSHPCGPAPKRLQV', 'SFHLHCWVCMCCWSTTGCTDGDYDIPEWIW', 'YCYDQWWTMKHMIKPFLRMDARYWEDVHTK', 'FNDINLGRVLYTAVLEFKEEVFKLYHMHKT', 'SKCDQKCAMFKGRVQVAEDFVCNWVFQFCL', 'NCNHIENVQYFIGGQAGMQIKGEPCSIHRN', 'LIIAHPMKDKNTPVMAEKGWKCEYQNMQYT', 'EPWHKCQATVHNQDMYMELTLQMPLVFHQP', 'GYWLPVALLHQWYMRRRHTSGDLTYMDILI', 'HFACISYDRQWHPSPIFAEQIGTRCVIERF', 'RTVYMRYTQVRGSRKIKTSIKRDLIKMMVD', 'FFIPFHDQQMVRQCHQPWAWPSANLPQVVY', 'ISIKQSAPMPGRFYVAPWWADQFRGCKPMH', 'RMMPKQKDSAVCNIDCAIHAYFIFSEWHRK', 'NGYYEGLEWALWPPHDWIELYEWCNVQNDT', 'MAQSEQNRFQGTKYVSRQWKMIDKRIRWYP', 'MASMGSHNKMKYKVATHDIQSVISSRADLI', 'PILWNSVTNQVMNRKLKIEHMEVGHHSKWT', 'YLEHLINGLAVFKCCVLFSEAWLSSRMGCK', 'SEDPSDWCFFWLDIEVQYYYITPRRLWQLW', 'YCYEHHKDGIGVDGAQRYSLCILLRDIKWH', 'QEVIFKFDCGLYWLRERLPKTVSRDYCQMY'], 'peptides_60': ['KADIWWAKWCGSTRKGWQSDSNQMMEGMQSLPVCRDMKMEPTAVRQCHTNYSRCHKVFLR', 'SEAYIGLVAVQDIEREFSLTKQSSIRVFPHYTFDKQMTKALLWWSFRVSNMVVPRMHIWP', 'IQCMSPPFSCFTWMERETRAFQFDSKMYPDMVPMSVCYDILIDQEERGLACMCLNNQFIT', 'QWGGGDYPYISWFIRKRKARLVGDRNWLQKRLHPSEIPWNWLLAPKAWCYSLIYNIHYKF', 'ECLRCWNFDLMQGHFVNTTKGKSLMERDFIPVNDPAKVERNKWPNEISAYVMYIDRLQEF', 'CCLSEEIVFPRNVQWFQESYQKCNHRRINENVNCPKHERDHYACMIFWHDVHWHIMFYAK', 'FFVKGEAFANIWMAGKCFQTEDSRNTWERTIYCTLRACSPQESRDDMYFDFKYWVMPYTL', 'RTYQEEVHQRIQMRPQEMQMKNFSDDDDQENFVCWVVMEQNQCLYLNEWTHFSIENVNEK', 'WIQVYYVAYKAGKLMNAGFWPDFADTHPQRMGNLMWYDCFGYCDKRQSYRQKHTENQELW', 'STLCIPYCAHLHFKLMEASQGFPVITVNDPCQARDMWQWPQLEPAMGYRNDQEIQWPTDP', 'LMIMGDTETTHNNFIEFKHGYFDGSRWWRWYMMFRDSRLKWCNTDLRRCCNLDDYYTPRW', 'VCRWHMYSTFCREMDTGCIRRTTYGNNLPQMYCMDMEVPLKYFMDWFNLPFYDLVPMFTD', 'QTNANLGHMSHIFFDLETVTCMYFYPFGGYGRCQNIRYLRIVILSHNWRRLPTTQGHYFK', 'CSNVETELDGKRTFQDIRNAQCPTNIPDNIAMEMFFCLSFSRYADAKHFVYTQELILECI', 'QYRDESYVATWIFLQAYNIWQGDTNDTVTTVAPSCPNKANDNIEWMFCNVMGRSGFDRCL', 'HCHCMLTPVSKCHLNCMKENQPRPMGSSNTKDQDQYGVLMEDMLLRYQGRNRCNYQKCDP', 'NTGAFYRCFDINNPWCYFRNNRDWFTNPMKIEAGSTPVEKKRHYLSHEFDRGRDMNDVVL', 'LGGNTIEHFISANVWNRVFYDDLPSTQQWDFMDRRTNFVWGFQTCETFLGGMINTLDKHV', 'KFLYVDTGWWFGYYMWCADCWKHWQYASVLLSIPLRDCGRQSRHMYFMMNPFNTVEMIRE', 'KRIFECLPYQIGMWMHGSTRSLSADPTRIHWNCCLSYSLVAEQFKNPNCPCWVHNVLDPT', 'RVKYYEFEPNMVNFHYTPTCCCFMSTRFYTFMYMGPYLWMTTVSWLSANMEQWLAYSKWW', 'ICWSGTYPFICWEHARMQFQHQTYSCFTHVMSTPMGRVMVNKYSHIKVLILLHSMSNVKL', 'EWVPPNFLCLDNRKSHHVKVKFEYWIICTIICEQMSEFAVGQSSHLMLCDWIVCGQGCPS', 'GLCALWYEMLRVTSFTRKHEMGRKGAMLWHGYPQTMDPEGFSMIAKPIRKMLWWAKNICE', 'RLGPTLELNYIIFSFRYNQVSVHIYDTRTNDWECVTHWVFGMTREHWSDTRCRFTQRWCV', 'RLAPKAHWDCQNDVCDSCLQGFQNPRPPDVFNEGVPTFIAALRVQVPIIRNFKHECQYAI', 'HDEYCRYCICPRIVHCFTLIWMWYMILFTIQLKCVWGQVSCNPTMQQFLPGVSIILFRCV', 'QQVTFPIKHMDRNDVHCKPYYCDHWVHSHMLAHHESIYHPIVMLPRVNLKNTSRESMHNM', 'QCWIFAKVWWQLFHMIPWISVMKSSRGNGFVSGVCTCDCAQFIDFAHTRNCYYSSAAVVQ', 'AATKVLATQGEETFIHYTKNKPDNPRWIILDCDPPPVSCAGDSQMWETCIHWSKCDKVWC'], 'peptides_200': ['GMAHWFPDLGWIWPVMPFDTNCEQIDMYYYPMAKRSINVPQGWPDYLIDDKFPFPMNEDALRNKEFDGQRVVTQEADNVDYYMPALQPDVIWTGPGFKLKSFDGQKQLSDNKISYYHREFLAPMYPMRMQYFLMYHSMGPMLSWIMPKPNEWHWVGVARHRLDQSFLIKFQPDRYSWPVTQVCNVYDEINGYCWPMQEAE', 'KITTVWWIRNPRWTFNASELQDEFNLMRHTSNSERRMDLCEAMEGITGVGMVQRIPGGQPAYHRWQPAHHKDWEVGNMHREKSTMYPYPWENNRYGLYWDFMEILEGNFTPQYFWPQGSVGVGSLFGMRYCNASFHPVTSQSQRSGDWAILCKIVLGRWSVTEWEKVNVCRVHQEILCRKNDREIHWNYQGYFHHCWNVK', 'YVGMLLWKTEFQCKFFIFMIPSFWKQPRDDPTKNRSMWADRNDVPHQHSKMLMVWFWSMCCERAEGRRAQHFLGKDNKDNGCPLIQDEAHSDFWITRAAMEQFSDIPDEEMNLFPFFDTWAYGRNHFQYRHDEFEWPNQMFIKDIVYYYLALHTYTHPLCISPEISYDTANMFPWQNVGSDAWDAKHCCPTLTQQPDVVY', 'FKDLDTHFVMPWDLQICIDQERYYCLGEAFAGSNTTKGNFKEAMQKTDKWDSRTNCSWGNGKEWEITACAICSNPFGCVQIMIQMKDWNETCGITCPDRLLMDVRANHLWLYIRNWSHVIFAQAIVNAMAPLEHTIQSCFKDCITQNRDWETFPDWWCQFILKMPMMRKIDHFWEFEGRRMQEVNHRLRKEDGLYCHMFD', 'INPTCLKGAPRVVIEREFEACIFHPNDWWKDADHRFDMECRCGWQPSAPQGNHGKKRFCYYYILSQVSCDKPFQHTIVAPNSVSNWTMPKGAMYIAKCSTNWIGEIIKVCIWPNGGIWMNWANWWFWHSVLGSCDCIYIATSAMYHFMGMCAFWFETNDNPWEMLMFGQSMGVYNIWGPLLFGAWPWCGYMYIWESFMDI', 'NMGDMRAKHIDNKEACPRQGQSPNVPESWIGRDCLAMKEDMGPGDVDMYYSAQGYQGCEMHHQVVKLLIECPWVSFCNAQDLYSHEAHGLDSELPSSKDVPGNPNGRCKRRKIKWCFEDNVQWIVCPTQVSWISLDPCTWTWYFERGGHHFCQDQHFYKMDDPVPVMKTRAYWTQEQFFWWWEEWELVNQKPSWYSCGKP', 'FYYPCPMICSKNAMLLKSEIFLRMKQYDHRHQSTNCTGDLTPFTWAGHHCICRCNHKNRTPEAINSYRGSWVNNGKDLAPCGWHIIHKQTAASFGYAIKYLKQPNRKHRLTYPWEATNVYYLLESDMKMKKLHFTICYPMFASLKQPPCWWHMIVSNTLGVGLESFKVGMDINILQMNKWLRESCWWYDSHTEPTLQCFF', 'HMQWRFMGDSMGMCARKHGWGSDFYQQPQSPACVHNAMTHAAIINLFEPTWLGDCLLRTYTMQFMSNHGPAIIFHAWTGENCPKVYCYCEACEQRPEVKSFHALQETKYYFQETYELEESHYHKTHNQLGCVSHSMIAADEWSFDTDEKIRLKRCEGCLNMQEECAFGMNRYKDNMGEPPRKPSQGEFCGEQWSWRGYPN',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       'YAFSSEQRCDKMATWWIMTTYEQISNPFVYCAGTSSGDSMIMKCTIVPPIDRRWRDSRMESAEPQCVVADYYLTVHRMNCIRMVYYSNREEIAMNLVTNECGSFQEKYHHEPHRHMEQCWERRWTFSATCVQWSTGWGFEPYYMTPQYIKPMLRFFQYTLVMVHHHYLNFGTVMENVSWWQVLQATEAPFCCHKGLKFCL', 'HVCNREYVIVPITLCPPQMVCAKHYRINWVYHHLRGDGGTEPCQKVKFGWKAMRFCFMYCYLSWVNDMTIGTDTGQVVPDNIHMMNLHYTSVAENRIYYICMPEPKVLATNTTRSCLHMTDEGVVADHHQEHVQDFARMCDDCGKVDWIKQPRPQMAPEVAYDWCDNTELLYDLRPPASGVIFPVLFLNAVVFECAWYPV', 'VDLHNHQTFGGIYKHEGWCVRVDLDKEHWSMNFIELYDHMSRMYLWFWWNMQGAMIIQKNFMSRRNLSVEGYDKFVHKDDATAWWPWHCVKVVSFNPIWLFRTTDPNTAIYGTFRGGWWFSNCISIDKNICHTNPSRCCMETKKWVWGPPNWDTKPITPNNSSYATFRGIDTKHFGGNYEIQMESSSHWGQAICFWWGFT', 'CWFCGKGTPYWALDHRYSSGIQYFWGYTKGMRYWDIPPFEAHTTQFYEGSYYCVTEDSFYVAQTQNCTQISPNWWEQFKSIDLYVQKHAAWTETAPHMQNEFQWKKVQWNYKPHQVVSGNVVSKLWNPFEIRGEHTPMVYCGPADFSYQDDKINDYCPPYTLYCGSRAHTLHCYTTIYGCNIAGDKPNPPWHTADDVLVW', 'NNKIYHRPWAKGQTEVDTLMETKVWKRPWSIMRRWASEKDPIIMQNTVAKILDPMDVGSMNHWKGHSHIIKHIHIYNFEEDSYAVCSNYMSWKSGTKPIWFCTQSVCTNPGRETRMAAHPWEMNYKGVKIKSYMNGSQHQNNPKRGWFWIEKIVQPHFFSAGQSFTVMSLKVWCPEGCHKSERMKNNVVKNAQENYHWWV', 'GLNMTSRDPYLRFGMQYWPDDGMIMMLKYPKRNWTRQGGAFIKDHGPEEDSVCAPTDEKYFDPLIILRFFTGACNMSRVKVRFVGWYRWQTVLNSVIDRLNQKFLAATFNLSVASSLAQLYIAVNHQVQPIGPPIKDQITYKLVKQHDGFLERYRKYSHMAFCVAGELKFRAIDFASHMQLSNRCMDFCKPDVSGHKPAE', 'IPRICHRETHSPLMGCVTEKSLHNCHEIQMAGKWEPIACWSYFNDIGSDYMCCNFVEFSIMVNRHAPNFKCSRVLVSHWGVNMRKYVGDTFRLKVNRATPGAYNYIMDVPHTSVFYLMQMEETDCFGCHESHECWPSTYWKCNIYDAHSDRCNVQNCYKTCDLDHTEEIVPHHTIWGVVQEWNRQEGGVPTMGVYRNMVM', 'NQQMYIWVHPVKNRRPACLYATFLALIHMAKVTVWWFECRNFFKNWIIKLDWPWHDMSGSWEYLCWPDCMNQQEIYAPCLTCMVWFMTIFCPRYWTDIQLPFFMDSWCVPKDPTQFFSVHSPWHVYTIIDKQMWDEQQNNHMNYALGNYRYFRCIHNFDECIYFLAMELRSAMHVHHVTKVSYFAPWTCKGCLHYKCRAD', 'PKNEALPIPTEMSYVDGHTRVACITLMSPGANNNLITKCKPAVKIFMPFDPTYIQIWFQLYMRVFHFWVHFLTFQFWGMDVVEGMFAMQQLRKFHEFGAYYKYWYIYIIANDSFTYSNGPSSFGHICQAKQIHHDGRYSMRIQPCYPMPYWYVTCTERRCITVPCVPTCHLRPLLRGQLYCTFRRDTEGWVFPQMRAGRW', 'HRDKMGEDERNDTPTYGPVPCGMWFGFGCQLLRLGEFHAYKARSSVAYSIHWSRQRDYYAIVKYVHCGFCNCFCWYLMDCEQGGLYYWVGRWNCDLMNPDQVDLSFEKMTQTHHYCEWTDSYLQYMKTWYNFYWSTSSGYILHAEAREHYQQCMNVHAHLKDLLTVMAEMMPWYAGHMMSSCFSFRVMRQCTLWMVVAHW', 'MNDFKAMPVGWYPGYELMCKQDSINRLHTLGENCHDRTASTFHMSTLMFETFHCRPTEALCYDMRCETLAWLHMHHLKVMREKFGKEAYVTEHVNVMKFLWIGDLYMVRCFASCEPCDQPGYWRYNLMHVDRWFDRERLRSIIFYKNPGMMRSADSENSRGLNYWFTEPEMVDLVRPWQIYIVGSPDMHWQQWMVIGDWS', 'EWYRMVERGLPDYEYPMSCDHFWAFFRVLPYWRHHMLWLQNDWAYTPFLCNVCAVNELAIQWPMPPPQVHGSFHVPNQFLFFADAFSQFDFQRYQYGRTQVRPNIGQYAWSITKQVWNCCWSNEWSDFTKRTDTYDISDVWLYCMVASRTSWMQNLLGCYLWKCSWGWCLYALSDFTDKKFYKKKAEYGWFRNGKISGTC', 'MDFYFSQPIRGHWNCKECGRPSLSVIPPSKFTQALRPMTCEVNQYKMKKEKWPRIWHTMGMVAADAQETERNILKHCAYDCYHYEEDYFPWGEGKLRDRKQMKGDKCPPMCKKGRDSHYPGSEFVQHYERKECDDWKRASFACPKFMPWATSSQPDVIAPSEWVNMLPCDNVMDRLHGVCPHLPENSDRHFCHAWISPDV', 'LSVRACMCMCPEHTRVFWIDCFSASYCIFAGCLERYGWDEESYYIDHQMPMEWVFMHCWGMDEKFQGNVGRIWCFEYPGASDAAGDWLQSFHFKTRQIGYCYGSYDLNQAVIHETEYNVTIRHKCHEFSSGGCCNLHQKMYRCECVGGASTEDIRWWMQHMIEMIEIQHPIDSWSCQFHYRGPNFRHNKHMFCWCKFERR', 'QGMILYGYGWVIDQTSHWSRKAQIIMQWIWFWAQCCSTCQTPSERSIDVAQHFNLIDASLGRWWARRFPGNRADPMTCLQKYVWHDYMCTNCEPNRYCNNGVDVHFMIVESWHIMNKTQKCDNNRSTTESVVLRYNDHRDDPGLDEGKEFSFHTALQVFSNQRALHDAITMQWMMSWTVRRLWFLGKISNLCFNLRGYGV', 'LGGFGIECMWFRKNGHVCMNFNRVGVLEAPSFRMFAVTMLSLWFWRMESCFVELAPYIRNDMCYHWTIKHADVRDTPHSMYYTCNPFQNPNALNNLRVDHRQRLGQQFWYDFHLSTMDWPDAQKQGVRWFHGPLVSCLWLSVRIAAFKLSELQGSIAEKSDYNWSWQKSENTWAKGWCFMRFNGCKNQNCLLTDTHGEYG', 'VMMLKNEVWNFAFTLNSQMGEHFTIHVYTVVEQRDEFASNLNFRYTMGLAEIFFILFHFDQEDASQCHECTWCSEKCDLAEEYHWHGNADFKWNNGTYITWDEWATHHLGVAEHTSNWGREGNPQHTIQEMERETFSNLVCDMSEPLRYLRIVQLQHDSNGASEPRTDEFPPWEGDNHMHYPEIQSKWWKPNSYPSTKFR', 'EEKSSIFAECDSAGPYMFLYYEDTSRHLSSTKVMVVACQEPRMPRRCCGVLGSQFLPSEWSVVWSSVGTCPKSWPYNLMCAWCFNNWAMPEQNNQNCIIILWDDLEMGAVMCRQWTQKASWAMPWPMWESEHMSTMGYLNQHSDVHLKCLWPIYDWEWMKDWTSQHNDLTLQVMHQPKYTRVGATGWSHRKVYQWCTHNR', 'FIFLQQMDHQKLGKYIPIEFHAILRSVQQCHGKFAKKVGCSACDMYLDQNDPFIEWTETWTKSDIYEMMWPIQHFEGHKRQKWCSVNEMVQSIKFNSNLAYCCIKVPLNEVIRPAPKLDILHGRMQCKDSSQMQEGKTDNQYVMRACGRFAPHLMWDEGITFYQMRSFKGWMLHDQNGPPWIAAVYIDRHKGCPYQYKFD', 'NGWEATQRSEIHHKLSPFQHYHLHQGQFALKIYRINWRDASFMPHPQYKDEVCCMISNYYCAKTYPLPNFVCWGKGTSMRFDMTQFKEMCFSKNQLKYKTMQGMSFVRCHFCIGCSKGRQESCRNVSRSEFENDHLGGTKWWHWATWGQDISEMALEPNWEMFADRSRKYAMCYRMWFHCLMCDVYPDPKGIPDAHGPPL', 'FELSQLYFNENTHSRPSKWYQDQNYGQQDCTMRIFSTTDLRQDSLFFLITQLWCVDCTETQQERWKNKWDTAERGGPCDQLMWRRYKMGHGDYKEQVAAPEAGSRPYSLYYNPLDFFAHEAHAHSFIQVHDLRFSQAEGFRSSARWIHLWPCMAEQQSWYVLCSPSTWYSICTAQWMVDKQSESYNRQAGLHSNRITIWM', 'YRFLPQNSGYHLDSFGHGYSEQSLIHVCANKNGGTCDMQEYIEVISKMNCVKFTYECRREEYYEVCTEGEHNGLRTSEFNMFEHRQAISMLTGDKNQNIFTQIFQQQRTNARFATDDMMPGQCPCFWCTLQPVLMNAKTYFPRHVYYRNPHLDCVMPFTVLHDTVLTMGAAVWKILQTECNKTNECERLWARMIWWVYIN']}

prefix = "TTTATAATTTCTTCTTCCAGAA"  # IRES=22
suffix = "UUAAGCUA"
iresEND = 22


beam = 500
iters = 10
lr = 0.03
epsilon = 0.2
L = 2.5


def exec(props, input, cwd="./"):
    proc = subprocess.run(
        props, input=input + "\n", cwd=cwd,
        capture_output=True, text=True, check=True)
    out_lines = proc.stdout.splitlines()
    err_lines = proc.stderr.splitlines()
    return "\n".join(out_lines + err_lines).split("\n")


def find(lines, Q):
    for l in lines:
        if Q in l:
            return l.split(":")[1].strip()
    return None


def colored_ires(seq, start, color=31):
    return f"\033[1;{color}m{seq[0:start]}\033[m{seq[start+1:]}"


def count_cross_pairs(s: str, k: int):
    stack = []
    cross = 0
    for i, c in enumerate(s):
        if c == '(':
            stack.append(i)
        elif c == ')':
            j = stack.pop()
            cross += (j <= k) != (i <= k)
    return cross


def EFE(seq):
    res = exec([
        "./tools/LinearPartition/linearpartition", "-V", "-d0", "-b0"
    ], seq, "./")
    val = find(res, "Free Energy")
    return float(val.split(' ')[0])


def EnsembleWrapper(seq, init, eps, iresEND=0, lam=0.1):
    params = ["./bin/EnsembleDesign"]
    params += list(map(str, [beam, iters, lr, eps, 1, init]))
    params += ["--prefix", prefix, "--suffix",
               suffix, "--iresEND", str(iresEND),
               "--lambda", str(lam)]
    res = exec(params, seq, "./")
    mRNA = find(res, "Final mRNA")
    print(" ".join(params))

    # Cross-pairs are counted from RNAfold's structure (external). When iresEND=22 the C++ DP
    # forbids IRES-rest pairs (pair_blocked), so the optimizer's model has 0; RNAfold can still
    # predict such pairs -> crp can be >0.
    res = exec(["RNAfold", "--noPS"], mRNA, "./")
    struct = res[1].split(" ")[0]

    crp = count_cross_pairs(struct, 22)

    print(f" - mRNA:  {colored_ires(mRNA, 22)}")
    print(f"          {colored_ires(res[1], 22)}")
    print(f"   CROSS: {crp}  [for {iresEND}]")

    return crp, mRNA, struct


def frange(start, stop, step):
    x = start
    while x <= stop + 1e-12:
        yield x
        x += step


ts = datetime.now().strftime("%Y%m%d_%H%M%S")
res = open(f"test_{ts}.txt", 'w')
res.write("sid\tires\tEps\tLength\tCrosspairs\tCAI\tEFE\tmRNA\tStruct\n")

id = 1
for eps in frange(0.0, 1.0, 0.2):
    for set_name in data:
        for k, seq in enumerate(data[set_name]):
            tmp = exec([
                "./bin/LinearDesign_2D", f"{L:.2f}", "0", "codon_usage_freq_table_human.csv"
            ], seq, "./tools/LinearDesign/")
            init = find(tmp, "mRNA sequence")
            for iresEND in [0, 22]:
                crp, mRNA, struct = EnsembleWrapper(seq, init, eps, iresEND)
                cai_val = cai(mRNA)
                efe = EFE(mRNA)
                result_line = \
                    f"{id}\t{iresEND}\t{eps:.1f}\t{len(seq)}\t{crp}\t" + \
                    f"{cai_val:.3f}\t{efe:.3f}\t{mRNA}\t{struct}"
                print(result_line)
                res.write(result_line + "\n")
            id += 1

res.close()
